<template>
  <div>
    <b-container class="fluid mt-5" v-if="isAuthorized()">
      <b-row align-h="start">
        <b-col>
          <b-card>
            <label for="input-username">User:</label>
            <b-form-group description="Username of the data you want to view">
            </b-form-group>
            <b-form-input
              id="input-username"
              v-model="user"
              type="text"
              placeholder="username"
              required
              trim
            ></b-form-input>
          </b-card>
        </b-col>
      </b-row>
      <b-card v-if="allTodos !== undefined" class="mt-5">
        <b-row>
          <b-col>
            <div v-if="user === ''">
              <h1>All Todos</h1>
              <br />
              <div v-for="todos in allTodos" :key="todos._id">
                <h5>{{ todos.username || "AutoGenerated" }}</h5>
                <pre>{{ todos }}</pre>
              </div>
              <br />
            </div>
            <div v-else>
              <h1>{{ user }}'s To-Do history</h1>
              <pre>{{ allTodos }}</pre>
            </div>
          </b-col>
        </b-row>
      </b-card>
      <b-card v-if="allRewards !== undefined" class="mt-5">
        <b-row>
          <b-col>
            <div v-if="user === ''">
              <h1>All Rewards</h1>
              <br />
              <div v-for="Rewards in allRewards" :key="Rewards._id">
                <h5>{{ Rewards.username || "AutoGenerated" }}</h5>
                <pre>{{ Rewards }}</pre>
              </div>
              <br />
            </div>
            <div v-else>
              <h1>{{ user }}'s Rewards</h1>
              <pre>{{ allRewards }}</pre>
            </div>
          </b-col>
        </b-row>
      </b-card>
    </b-container>
    <b-container class="fluid" v-else>
      <b-row>
        <b-col cols="4">
          <div class="message mt-5">You are not authorized.</div>
        </b-col>
        <b-col cols="2"></b-col>
        <b-col cols="6">
          <div class="container">
            <div class="neon">403</div>
            <div class="door-frame">
              <div class="door">
                <div class="rectangle"></div>
                <div class="handle"></div>
                <div class="window">
                  <div class="eye"></div>
                  <div class="eye eye2"></div>
                  <div class="leaf"></div>
                </div>
              </div>
            </div>
          </div>
        </b-col>
      </b-row>
    </b-container>
  </div>
</template>

<script>
import Todo from "../../api/collections/Todo";
import Rewards from "../../api/collections/Rewards";

export default {
  data() {
    return {
      user: "",
      admin: ["abspence"],
      authorized: false,
    };
  },
  methods: {
    isAuthorized() {
      if (this.admin.indexOf(this.currentUser?.username) !== -1) {
        return true;
      }
      return false;
    },
  },
  meteor: {
    $subscribe: {
      // Subscribes to the 'threads' publication with no parameters
      allTodos: [],
      allRewards: [],
    },
    allTodos() {
      if (this.user !== "") {
        return Todo.find({ username: this.user }).fetch();
      } else {
        return Todo.find().fetch();
      }
    },
    allRewards() {
      if (this.user !== "") {
        return Rewards.find({ username: this.user }).fetch();
      } else {
        return Rewards.find().fetch();
      }
    },
    currentUser() {
      return Meteor.user();
    },
  },
};
</script>

<style scoped>
.message {
  font-family: "Poppins", sans-serif;
  font-size: 30px;
  color: white;
  font-weight: 500;
}
.message2 {
  font-family: "Poppins", sans-serif;
  font-size: 18px;
  color: white;
  font-weight: 300;
  width: 360px;
}

.neon {
  text-align: center;
  width: 300px;
  margin-top: 30px;
  margin-bottom: 10px;
  font-family: "Varela Round", sans-serif;
  font-size: 90px;
  color: #5be0b3;
  letter-spacing: 3px;
  text-shadow: 0 0 5px #6eecc1;
  animation: flux 2s linear infinite;
}
.trash {
  width: 170px;
  height: 220px;
  background-color: #585f67;
  top: 300px;
}
.can {
  width: 190px;
  height: 30px;
  background-color: #6b737c;
  border-radius: 15px 15px 0 0;
}
.door-frame {
  height: 495px;
  width: 295px;
  border-radius: 90px 90px 0 0;
  background-color: #8594a5;
  display: flex;
  justify-content: center;
  align-items: center;
}

.door {
  height: 450px;
  width: 250px;
  border-radius: 70px 70px 0 0;
  background-color: #a0aec0;
}

.eye {
  top: 15px;
  left: 25px;
  height: 5px;
  width: 15px;
  border-radius: 50%;
  background-color: white;
  animation: eye 7s ease-in-out infinite;
  position: absolute;
}
.eye2 {
  left: 65px;
}

.window {
  height: 40px;
  width: 130px;
  background-color: #1c2127;
  border-radius: 3px;
  margin: 80px auto;
  position: relative;
}

.leaf {
  height: 40px;
  width: 130px;
  background-color: #8594a5;
  border-radius: 3px;
  margin: 80px auto;
  animation: leaf 7s infinite;
  transform-origin: right;
}

.handle {
  height: 8px;
  width: 50px;
  border-radius: 4px;
  background-color: #ebf3fc;
  position: absolute;
  margin-top: 250px;
  margin-left: 30px;
}

.rectangle {
  height: 70px;
  width: 25px;
  background-color: #cbd8e6;
  border-radius: 4px;
  position: absolute;
  margin-top: 220px;
  margin-left: 20px;
}

@keyframes leaf {
  0% {
    transform: scaleX(1);
  }
  5% {
    transform: scaleX(0.2);
  }
  70% {
    transform: scaleX(0.2);
  }
  75% {
    transform: scaleX(1);
  }
  100% {
    transform: scaleX(1);
  }
}

@keyframes eye {
  0% {
    opacity: 0;
    transform: translateX(0);
  }
  5% {
    opacity: 0;
  }
  15% {
    opacity: 1;
    transform: translateX(0);
  }
  20% {
    transform: translateX(15px);
  }
  35% {
    transform: translateX(15px);
  }
  40% {
    transform: translateX(-15px);
  }
  60% {
    transform: translateX(-15px);
  }
  65% {
    transform: translateX(0);
  }
}

@keyframes flux {
  0%,
  100% {
    text-shadow: 0 0 5px #00ffc6, 0 0 15px #00ffc6, 0 0 50px #00ffc6,
      0 0 50px #00ffc6, 0 0 2px #b9ffe8, 2px 2px 3px #12e29c;
    color: #4bffef;
  }
  50% {
    text-shadow: 0 0 3px #00b58d, 0 0 7px #00b58d, 0 0 25px #00b58d,
      0 0 25px #00b58d, 0 0 2px #00b58d, 2px 2px 3px #006a60;
    color: #63d3ae;
  }
}
</style>
